function dphids = dPHIds(dx,dy,T1,T2,T3,T4)
%dPHIds
%    DPHIDS = dPHIds(DX,DY,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-09 14:56:56

%Version: 1.0 - Average Temperature Objective
dphids = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;(dx.*dy)./4.0;(dx.*dy)./4.0;(dx.*dy)./4.0;(dx.*dy)./4.0];
end
