function dphidg = dPHIdg(dx,dy,alpha,dalpha,T1,T2,T3,T4)
%dPHIdg
%    DPHIDG = dPHIdg(DX,DY,ALPHA,DALPHA,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-09 14:56:56

%Version: 1.0 - Average Temperature Objective
dphidg = 0.0;
end
