function phi = PHI(dx,dy,T1,T2,T3,T4)
%PHI
%    PHI = PHI(DX,DY,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-09 14:56:56

%Version: 1.0 - Average Temperature Objective
phi = (dx.*dy.*(T1+T2+T3+T4))./4.0;
end
